# Generated by Django 5.0.3 on 2024-03-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newscategorymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='news_price',
        ),
    ]
