# Generated by Django 5.0.3 on 2024-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_newsmodel_news_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_title',
            field=models.CharField(max_length=50),
        ),
    ]
